# --| Frenzy's Alacritty |-- #

# Colors

# Implementation of Colors
colors:
  primary:
    # for hard contrast: #1b1b23
    # for neutral contrast: #20202a
    # for soft contrast: #2c2e3e
    background:        &aquarium_bg '#20202a'
    foreground:        '#c8cedc'
    bright_foreground: '#a0a8b6'
    dim_foreground:    '#4c5664'

  cursor:
    style: Underline
    text:   CellBackground
    cursor: '#ebe3b9'


  vi_mode_cursor:
    text:   CellBackground
    cursor: '#ebe3b9'

  search:
    matches:
      foreground: '#000000'
      background: '#ffffff'

    focused_match:
     foreground: CellBackground
     background: CellForeground

    bar:
      background: None
      foreground: None

  line_indicator:
    foreground: None
    background: None

  selection:
    text:       CellBackground
    background: CellForeground

  bright:
    black:   '#3b3b4d'
    red:     '#ebb9b9'
    green:   '#caf6bb'
    yellow:  '#ebe3b9'
    blue:    '#cddbf9'
    magenta: '#f6bbe7'
    cyan:    '#b8dceb'
    white:   '#c8cedc'

  normal:
    black:   '#3b3b4d'
    red:     '#ebb9b9'
    green:   '#caf6bb'
    yellow:  '#ebe3b9'
    blue:    '#cddbf9'
    magenta: '#f6bbe7'
    cyan:    '#b8dceb'
    white:   '#c8cedc'  

  dim:
    black:   '#32302f'
    red:     '#cc9b9d'
    green:   '#a3ccad'
    yellow:  '#d1ba97'
    blue:    '#076678'
    magenta: '#c497b3'
    cyan:    '#86bfbc'
    white:   '#928374'

scrolling:
        history: 10000

        multiplier: 100

        faux_multiplier: 100

        auto_scroll: true

window:
        dimensions:
                columns: 100
                lines: 100

        padding:
                x: 10
                y: 10

tabspaces: 4

font:
        normal:
                family: Sauce Code Pro Nerd Font
                style: Regular
        italic:
                family: Sauce Code Pro Nerd Font
                style: Italic
        bold:
                family: Source Code Pro
                style: Bold Italic
        
        size: 15
        history: 10000
        offset:
                x: -1
                y: 1
        glyph_offset:
                x: 0
                y: 0

env:
        WINIT_X11_SCALE_FACTOR: '1.0'


key_bindings:
        - { key: V,        mods: Control,       action: Paste                   }
        - { key: C,        mods: Control,       action: Copy                    }
        - { key: Paste,                         action: Paste                   }
        - { key: Copy,                          action: Copy                    }
        - { key: Q,        mods: Alt,       action: Quit                        }
        - { key: N,        mods: Alt,       action: SpawnNewInstance            }
        - { key: Return,   mods: Control,       action: ToggleFullscreen        }
        - { key: Equals,   mods: Control,       action: IncreaseFontSize        }
        - { key: Minus, mods: Control,          action: DecreaseFontSize        }
        - { key: S,        mods: Control|Shift, chars: "\x1b[83;5u"             }

cursor:
        style: underline

mouse:
        double_click: { threshold: 300 }
        hide_when_typing: true

selection:
        semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>"

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

dynamic_title: false
dynamic_padding: false
